CREATE TABLE IF NOT EXISTS HOSPITAL (
  IdHOSPITAL INT IDENTITY(1,1) PRIMARY KEY,
  RAZAO_SOCIAL VARCHAR(45),
  NOME_FANTASIA VARCHAR(100),
  CNPJ VARCHAR(18),
  INSCRICAO_ESTADUAL INT,
  INSCRICAO_MUNICIPAL INT,
  SITE VARCHAR(45),
  EMAIL_EMPRESA VARCHAR(50),
  LOGRADOURO VARCHAR(45),
  NUMERO INT,
  BAIRRO VARCHAR(45),
  CIDADE VARCHAR(45),
  ESTADO CHAR(2),
  TELEFONE CHAR(9),
  CELULAR CHAR(9),
  RESPONSAVEL VARCHAR(45),
  TELEFONE RESP CHAR(9),
  EMAIL RESP VARCHAR(100),
  CHAVE_SEGURANÇA_CHAVE VARCHAR(20)
  );

CREATE TABLE IF NOT EXISTS USUARIO (
  IdUSUARIO INT IDENTITY(1,1) PRIMARY KEY,
  NOME_USUARIO VARCHAR(45),
  USUARIO VARCHAR(45),
  SENHA VARCHAR(45),
  EMAIL VARCHAR(45),
  TIPO VARCHAR(45),
  fKHOSPITAL INT,
  CONSTRAINT fkHOSPITAL FOREIGN KEY (fkHOSPITAL) REFERENCES HOSPITAL (idHOSPITAL)
);

CREATE TABLE IF NOT EXISTS PRE_CHECK_IN (
  idPRE_CHECK-IN INT IDENTITY(1,1) PRIMARY KEY,
  NOME VARCHAR(45),
  CPF VARCHAR(14),
  RG VARCHAR(12),
  IDADE INT,
  EMAIL VARCHAR(45),
  PARENTESCO VARCHAR(45),
  DATA_CADASTRO DATETIME,
  fkHOSPITAL INT,
  CONSTRAINT fkHOSPITAL FOREIGN KEY (fkHOSPITAL) REFERENCES HOSPITAL (idHOSPITAL)
  );

CREATE TABLE IF NOT EXISTS TOTEM (
  idTOTEM INT IDENTITY(1,1) PRIMARY KEY,
  LOCALIZAÇÃO VARCHAR(45),
  NOME VARCHAR(45),
  STATUS_ATUAL VARCHAR(45),
  fkHOSPITAL INT,
  CONSTRAINT fkHOSPITAL FOREIGN KEY (fkHOSPITAL) REFERENCES HOSPITAL (idHOSPITAL)
  );

CREATE TABLE IF NOT EXISTS COMPONENTE (
  idCOMPONENTE INT IDENTITY(1,1) PRIMARY KEY,
  TIPO VARCHAR(45),
  fkSERVIDOR INT,
  CONSTRAINT fkSERVIDOR FOREIGN KEY (fkSERVIDOR) REFERENCES TOTEM (idTOTEM)
  );

CREATE TABLE IF NOT EXISTS HISTORICO (
  idHISTORICO INT IDENTITY(1,1) PRIMARY KEY,
  DATA_ATUAL DATETIME,
  UNIDADE VARCHAR(45),
  CONSUMO DOUBLE,
  DISPONIVEL DOUBLE,
  TOTAL DOUBLE,
  fkCOMPONENTE INT,
  CONSTRAINT fkCOMPONENTE FOREIGN KEY (fkCOMPONENTE) REFERENCES COMPONENTE (idCOMPONENTE)

